disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - explicit_acl
  - explicit_top_level_acl
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - yoda_condition

excluded:
  - Pods
  - .build
  - DerivedData
  - personalos-ios-v2.xcodeproj
  - personalos-ios-v2Tests
  - personalos-ios-v2UITests

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - i
    - j
    - x
    - y

# Swift Concurrency Checks
strict_concurrency: warn

# Custom Rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use Logger instead of print()"
    severity: warning
    
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Use safe casting with 'as?' instead"
    severity: error
    
  no_force_try:
    name: "No Force Try"
    regex: "try!"
    message: "Handle errors properly with do-catch"
    severity: error

reporter: "xcode"
